CREATE DATABASE IF NOT EXISTS shopping_cart_localization
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE shopping_cart_localization;

CREATE TABLE IF NOT EXISTS cart_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    total_items INT NOT NULL,
    total_cost DOUBLE NOT NULL,
    language VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cart_record_id INT,
    item_number INT NOT NULL,
    price DOUBLE NOT NULL,
    quantity INT NOT NULL,
    subtotal DOUBLE NOT NULL,
    FOREIGN KEY (cart_record_id) REFERENCES cart_records(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS localization_strings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(100) NOT NULL,
    value VARCHAR(255) NOT NULL,
    language VARCHAR(10) NOT NULL
);

DELETE FROM localization_strings;

INSERT INTO localization_strings (`key`, value, language) VALUES
('prompt_num_items', 'Enter the number of items to purchase:', 'en_US'),
('prompt_price', 'Enter the price for item:', 'en_US'),
('prompt_amount', 'Enter the quantity for item:', 'en_US'),
('prompt_total', 'Total cost:', 'en_US'),
('title', 'Roberto Caretto - Shopping Cart Calculator', 'en_US'),
('label_language', 'Language', 'en_US'),
('lang_en', 'English', 'en_US'),
('lang_fi', 'Finnish', 'en_US'),
('lang_sv', 'Swedish', 'en_US'),
('lang_ja', 'Japanese', 'en_US'),
('lang_ar', 'Arabic', 'en_US'),
('label_num_items', 'Enter number of items:', 'en_US'),
('prompt_num_items_short', 'e.g. 3', 'en_US'),
('btn_prepare_items', 'Prepare Items', 'en_US'),
('label_item_inputs', 'Item inputs', 'en_US'),
('btn_calculate_all', 'Calculate Totals', 'en_US'),
('label_item', 'Item %d', 'en_US'),
('label_item_total', 'Total:', 'en_US'),
('label_price', 'Enter price for item:', 'en_US'),
('label_quantity', 'Enter quantity for item:', 'en_US'),
('btn_add_item', 'Add Item', 'en_US'),
('result_total', 'Total cost: %.2f', 'en_US'),
('overall_total', 'Total cost: %.2f', 'en_US'),
('error_num_items', 'Please enter a valid item count (1-50)', 'en_US'),
('error_invalid_input', 'Please enter valid positive numbers', 'en_US'),
('error_save_cart', 'Data was calculated but not saved', 'en_US'),
('current_time', 'Current Time: %s', 'en_US'),
('time_format', 'HH:mm:ss', 'en_US'),

('prompt_num_items', 'Syötä ostettavien tuotteiden määrä:', 'fi_FI'),
('prompt_price', 'Syötä tuotteen hinta:', 'fi_FI'),
('prompt_amount', 'Syötä tuotteen määrä:', 'fi_FI'),
('prompt_total', 'Kokonaishinta:', 'fi_FI'),
('title', 'Roberto Caretto - Ostoskorilaskin', 'fi_FI'),
('label_language', 'Kieli', 'fi_FI'),
('lang_en', 'Englanti', 'fi_FI'),
('lang_fi', 'Suomi', 'fi_FI'),
('lang_sv', 'Ruotsi', 'fi_FI'),
('lang_ja', 'Japani', 'fi_FI'),
('lang_ar', 'Arabia', 'fi_FI'),
('label_num_items', 'Syötä ostettavien tuotteiden määrä:', 'fi_FI'),
('prompt_num_items_short', 'esim. 3', 'fi_FI'),
('btn_prepare_items', 'Luo rivit', 'fi_FI'),
('label_item_inputs', 'Tuoterivit', 'fi_FI'),
('btn_calculate_all', 'Laske yhteensä', 'fi_FI'),
('label_item', 'Tuote %d', 'fi_FI'),
('label_item_total', 'Yhteensä:', 'fi_FI'),
('label_price', 'Syötä tuotteen hinta:', 'fi_FI'),
('label_quantity', 'Syötä tuotteen määrä:', 'fi_FI'),
('btn_add_item', 'Lisää tuote', 'fi_FI'),
('result_total', 'Kokonaishinta: %.2f', 'fi_FI'),
('overall_total', 'Kokonaishinta: %.2f', 'fi_FI'),
('error_num_items', 'Syötä kelvollinen tuotteiden määrä (1-50)', 'fi_FI'),
('error_invalid_input', 'Syötä kelvolliset positiiviset numerot', 'fi_FI'),
('error_save_cart', 'Data laskettiin, mutta sitä ei voitu tallentaa', 'fi_FI'),
('current_time', 'Nykyinen aika: %s', 'fi_FI'),
('time_format', 'HH:mm:ss', 'fi_FI'),

('prompt_num_items', 'Ange antalet varor att köpa:', 'sv_SE'),
('prompt_price', 'Ange priset för varan:', 'sv_SE'),
('prompt_amount', 'Ange mängden varor:', 'sv_SE'),
('prompt_total', 'Total kostnad:', 'sv_SE'),
('title', 'Roberto Caretto - Kundvagnskalkylator', 'sv_SE'),
('label_language', 'Språk', 'sv_SE'),
('lang_en', 'Engelska', 'sv_SE'),
('lang_fi', 'Finska', 'sv_SE'),
('lang_sv', 'Svenska', 'sv_SE'),
('lang_ja', 'Japanska', 'sv_SE'),
('lang_ar', 'Arabiska', 'sv_SE'),
('label_num_items', 'Ange antalet varor att köpa:', 'sv_SE'),
('prompt_num_items_short', 't.ex. 3', 'sv_SE'),
('btn_prepare_items', 'Skapa rader', 'sv_SE'),
('label_item_inputs', 'Varurader', 'sv_SE'),
('btn_calculate_all', 'Beräkna totaler', 'sv_SE'),
('label_item', 'Vara %d', 'sv_SE'),
('label_item_total', 'Totalt:', 'sv_SE'),
('label_price', 'Ange priset för varan:', 'sv_SE'),
('label_quantity', 'Ange mängden varor:', 'sv_SE'),
('btn_add_item', 'Lägg till vara', 'sv_SE'),
('result_total', 'Total kostnad: %.2f', 'sv_SE'),
('overall_total', 'Total kostnad: %.2f', 'sv_SE'),
('error_num_items', 'Ange ett giltigt antal varor (1-50)', 'sv_SE'),
('error_invalid_input', 'Ange giltiga positiva nummer', 'sv_SE'),
('error_save_cart', 'Uppgifterna beräknades men sparades inte', 'sv_SE'),
('current_time', 'Aktuell tid: %s', 'sv_SE'),
('time_format', 'HH:mm:ss', 'sv_SE'),

('prompt_num_items', '購入する商品の数を入力してください:', 'ja_JP'),
('prompt_price', '商品の価格を入力してください:', 'ja_JP'),
('prompt_amount', '商品の数量を入力してください:', 'ja_JP'),
('prompt_total', '合計金額:', 'ja_JP'),
('title', 'Roberto Caretto - ショッピングカート計算機', 'ja_JP'),
('label_language', '言語', 'ja_JP'),
('lang_en', '英語', 'ja_JP'),
('lang_fi', 'フィンランド語', 'ja_JP'),
('lang_sv', 'スウェーデン語', 'ja_JP'),
('lang_ja', '日本語', 'ja_JP'),
('lang_ar', 'アラビア語', 'ja_JP'),
('label_num_items', '購入する商品の数を入力してください:', 'ja_JP'),
('prompt_num_items_short', '例: 3', 'ja_JP'),
('btn_prepare_items', '行を作成', 'ja_JP'),
('label_item_inputs', '商品入力', 'ja_JP'),
('btn_calculate_all', '合計を計算', 'ja_JP'),
('label_item', '商品 %d', 'ja_JP'),
('label_item_total', '小計:', 'ja_JP'),
('label_price', '商品の価格を入力してください:', 'ja_JP'),
('label_quantity', '商品の数量を入力してください:', 'ja_JP'),
('btn_add_item', '商品を追加', 'ja_JP'),
('result_total', '合計金額: %.2f', 'ja_JP'),
('overall_total', '合計金額: %.2f', 'ja_JP'),
('error_num_items', '有効な商品数を入力してください（1-50）', 'ja_JP'),
('error_invalid_input', '有効な正の数値を入力してください', 'ja_JP'),
('error_save_cart', 'データは計算されましたが、保存されませんでした', 'ja_JP'),
('current_time', '現在時刻: %s', 'ja_JP'),
('time_format', 'HH:mm:ss', 'ja_JP'),

('prompt_num_items', 'أدخل عدد العناصر:', 'ar_AR'),
('prompt_price', 'أدخل سعر العنصر:', 'ar_AR'),
('prompt_amount', 'أدخل كمية العنصر:', 'ar_AR'),
('prompt_total', 'التكلفة الإجمالية:', 'ar_AR'),
('title', 'حاسبة سلة التسوق / Roberto Caretto', 'ar_AR'),
('label_language', 'اللغة', 'ar_AR'),
('lang_en', 'الإنجليزية', 'ar_AR'),
('lang_fi', 'الفنلندية', 'ar_AR'),
('lang_sv', 'السويدية', 'ar_AR'),
('lang_ja', 'اليابانية', 'ar_AR'),
('lang_ar', 'العربية', 'ar_AR'),
('label_num_items', 'أدخل عدد العناصر:', 'ar_AR'),
('prompt_num_items_short', 'مثال: 3', 'ar_AR'),
('btn_prepare_items', 'إنشاء الصفوف', 'ar_AR'),
('label_item_inputs', 'مدخلات العناصر', 'ar_AR'),
('btn_calculate_all', 'احسب الإجماليات', 'ar_AR'),
('label_item', 'العنصر %d', 'ar_AR'),
('label_item_total', 'الإجمالي:', 'ar_AR'),
('label_price', 'أدخل سعر العنصر:', 'ar_AR'),
('label_quantity', 'أدخل كمية العنصر:', 'ar_AR'),
('btn_add_item', 'أضف عنصرًا', 'ar_AR'),
('result_total', 'التكلفة الإجمالية: %.2f', 'ar_AR'),
('overall_total', 'التكلفة الإجمالية: %.2f', 'ar_AR'),
('error_num_items', 'يرجى إدخال عدد عناصر صالح (1-50)', 'ar_AR'),
('error_invalid_input', 'يرجى إدخال قيم رقمية موجبة صالحة', 'ar_AR'),
('error_save_cart', 'تم حساب البيانات ولكن لم يتم حفظها', 'ar_AR'),
('current_time', 'الوقت الحالي: %s', 'ar_AR'),
('time_format', 'HH:mm:ss', 'ar_AR');
